databases:
  - engine: PG
    name: db
    num_nodes: 1
    size: db-s-dev-database
    version: "12"
name: sample-craft-cms
services:
  - name: sample-craft-cms
    git:
      branch: master
      repo_clone_url: https://github.com/espensgr/do-craft-cms.git
    envs:
      - key: APP_ID
        value: "CraftCMS--53c6334c-f04c-4231-91f3-06ee320b6638"
        type: "SECRET"
      - key: SECURITY_KEY
        value: "gt3oIoO43UhSkQiBcmThfdLMwy7fTV4S"
        type: "SECRET"
      - key: DB_DSN
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
    dockerfile_path: Dockerfile
    output_dir: /app
